app_name/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static
__author__ = 'user'


urlpatterns = [
    # ex: /app_name/
    url(r'^$', views.IndexView.as_view(), name='index'),
    # ex: /app_name/5/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    # ex: /app_name/5/results/
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultView.as_view(),
        name='results'),
    # ex: /app_name/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
  #  static(settings.STATIC_URL),
]

my_calc/urls.py
from django.conf.urls import url
from my_calc.views import get_name

urlpatterns = [
    url(r'^$', get_name, name='name'),
    ]

test_proj/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^app_name/', include('app_name.urls', namespace="app_name")),
    url(r'app_author/', include('app_author.urls', namespace="app_author")),
    url(r'app_adress_book/country/', include('app_adress_book.urls',
                                     namespace="app_adress_book")),
    url(r'^test_form_app/', include('test_form_app.urls',
                                     namespace="test_form_app")),
    url(r'^test_model_form/', include('test_model_form.urls',
                                     namespace="test_model_form")),
    url(r'^my_forms_app/', include('my_forms_app.urls',
                                     namespace="my_forms_app")),
    url(r'^my_calc/', include('my_calc.urls',
                                     namespace="my_calc")),
]

app_name/models.py
import datetime

from django.db import models
from django.utils import timezone


# Create your models here.
class Question(models.Model):

    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        """__unicode__ on Python2"""
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently'


class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        """__unicode__ on Python2"""
        return self.choice_text

app_name/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import Question, Choice
from django.core.urlresolvers import reverse
from django.views import generic


# Create your views here.
class IndexView(generic.ListView):
    template_name = 'apps/index.html'
    context_object_name ='latest_question_list'

    def get_queryset(self):
        """Return last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['title'] = "app_name"
        return context


class DetailView(generic.DetailView):
    model = Question
    template_name = 'apps/detail.html'

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        context['title'] = "app_name"
        return context


class ResultView(generic.DetailView):
    model = Question
    template_name = 'apps/results.html'

    def get_context_data(self, **kwargs):
        context = super(ResultView, self).get_context_data(**kwargs)
        context['title'] = "app_name"
        return context


def vote(request, question_id):
    p = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form
        return render(request, 'apps/detail.html', {
            'question': p,
            'error_message': "You didn't select a choice.",
            'title': 'app_name',
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('app_name:results', args=(p.id,)))

app_name/templates/apps/detail.html
{% extends "base_template.html" %}
{% block title %}
   {{ title }}
{% endblock %}
{% block body_app %}

<h1>{{ question.question_text }}</h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'app_name:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id}}" />
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
    {% endfor %}
    <input type="submit" value="Vote" />
</form>
{% endblock %}

app_name/templates/apps/index.html
{% extends "base_template.html" %}
{% block title %}
   {{ title }}
{% endblock %}
{% block body_app %}


{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
            <li>
                <a href="{% url 'app_name:detail' question.id %}">
                    {{ question.question_text }}
                </a>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No apps are available.</p>
{% endif %}
{% endblock %}

app_name/templates/apps/results.html
{% extends "base_template.html" %}
{% block title %}
   {{ title }}
{% endblock %}
{% block body_app %}

<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }}
        vote {{choice.votes|pluralize }}</li>
    {% endfor %}
</ul>

<a href="{% url 'app_name:detail' question.id %}">Vote again?</a>
{% endblock %}