my_calc/urls.py
from django.conf.urls import url
from my_calc.views import get_name

urlpatterns = [
    url(r'^$', get_name, name='name'),
    ]

my_forms_app/urls.py
from django.conf.urls import url
from .views import get_name, AuthorsListView, ArticleView, ArticleListView
from .views import ArticleDelete, delete_all_article

urlpatterns = [
    url(r'^$', get_name, name='name'),
    url(r'^list_authors', AuthorsListView.as_view(), name='list_authors_view'),
    url(r'^add_article', ArticleView.as_view(), name='add_article'),
    url(r'^list_articles', ArticleListView.as_view(), name='list_articles'),
    url(r'^delete_article/(?P<pk>[0-9]+)/', ArticleDelete.as_view(),
        name='delete_article'),
    url(r'^delete_all_article', delete_all_article, name='delete_all'),
    ]

test_proj/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^app_name/', include('app_name.urls', namespace="app_name")),
    url(r'app_author/', include('app_author.urls', namespace="app_author")),
    url(r'app_adress_book/country/', include('app_adress_book.urls',
                                     namespace="app_adress_book")),
    url(r'^test_form_app/', include('test_form_app.urls',
                                     namespace="test_form_app")),
    url(r'^test_model_form/', include('test_model_form.urls',
                                     namespace="test_model_form")),
    url(r'^my_forms_app/', include('my_forms_app.urls',
                                     namespace="my_forms_app")),
    url(r'^my_calc/', include('my_calc.urls',
                                     namespace="my_calc")),
]

my_forms_app/models.py
from django.db import models


# Create your models here.
class AuthorTest(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    birth_date = models.DateField(blank=True, null=True)

    def __str__(self):
        return self.first_name + self.last_name


class ArticleTest(models.Model):
    pub_date = models.DateField()
    headline = models.CharField(max_length=100)
    content = models.TextField()
    reporter = models.ForeignKey(AuthorTest)

my_forms_app/forms.py
from django.forms import ModelForm
from .models import AuthorTest, ArticleTest


class AuthorForm(ModelForm):
    class Meta:
        model = AuthorTest
        fields = ['first_name', 'last_name', 'birth_date']


class ArticleForm(ModelForm):
    class Meta:
        model = ArticleTest
        fields = ['pub_date', 'headline', 'content', 'reporter']

my_forms_app/views.py
from django.forms import modelformset_factory
from django.shortcuts import render
from django.views import generic
from .forms import AuthorForm, ArticleForm
from .models import AuthorTest, ArticleTest
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse, reverse_lazy


class MyMixinClass(object):
    def get_context_data(self, **kwargs):
        print 123
        context = super(MyMixinClass, self).get_context_data(**kwargs)
        context['title'] = "my_forms_app"
        return context


def delete_all_article(request):
    ArticleTest.objects.all().delete()
    return HttpResponseRedirect(reverse('my_forms_app:list_articles'))


def get_name(request):
    formset_cls = modelformset_factory(AuthorTest, form=AuthorForm, extra=3)
    if request.method == 'POST':
        formset = formset_cls(request.POST)
        if formset.is_valid():
            formset.save()
        return HttpResponseRedirect(reverse('my_forms_app:list_authors_view'))
    else:
        formset = formset_cls()
    return render(request, 'author_form.html', {'formset': formset,
                                                'title': "my_forms_app"})


class AuthorsListView(MyMixinClass, generic.ListView):
    template_name = 'app/list_authors.html'
    context_object_name = 'author_list'
    model = AuthorTest


class ArticleView(MyMixinClass, generic.FormView):
    template_name = 'app/add_article.html'
    form_class = ArticleForm
    success_url = reverse_lazy('my_forms_app:list_articles')

    def form_valid(self, form):
        form.save()
        return super(ArticleView, self).form_valid(form)


class ArticleListView(MyMixinClass, generic.ListView):
    template_name = 'app/list_articles.html'
    context_object_name = 'article_list'
    model = ArticleTest


class ArticleDelete(MyMixinClass, generic.DeleteView):
    template_name = 'app/articletest_confirm_delete.html'
    model = ArticleTest
    success_url = reverse_lazy('my_forms_app:list_articles')

my_forms_app/templates/app/add_article.html
{% extends "base_template.html" %}
{% block title %}
   {{ title }}
{% endblock %}
{% block body_app %}
<form action="" method="post">
    {% csrf_token %}

  {% for field in form %}
    <div class="fieldWrapper">
        <label>
          {{ field.label_tag }}
        </label>
        {{ field }}
    </div>
    {% endfor %}
    <br/>
    <input type="submit" class="btn btn-default" value="Add_article" />
</form>
{% endblock %}

my_forms_app/templates/app/articletest_confirm_delete.html
{% extends "base_template.html" %}
{% block title %}
   {{ title }}
{% endblock %}
{% block body_app %}
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>
{% endblock %}

my_forms_app/templates/app/list_articles.html
{% extends "base_template.html" %}
{% block title %}
    {{ title }}
{% endblock %}
{% load static %}
{% block links %}
   <!-- <link rel="stylesheet" href="{% static 'css/style_list_article.css' %}"/> -->
{% endblock %}
{% block body_app %}
{% if article_list %}
    <table class="table table-hover">
        {{ article_list.errors }}
        {% for article in article_list %}
            <tr>
                <td class="first_col">
                    <div class="author">
                        {{ article.reporter }}
                    </div>
                    <div class="pub_date">
                        {{ article.pub_date }}
                    </div>
                </td>
                <td class="second_col">
                    <div class="headline">
                        <p>{{ article.headline }}</p>
                    </div>
                    <div class="content">
                        <p>{{ article.content }}</p>
                    </div>
                </td>
                <td class="del_col">
                     <a class="del" href="{% url 'my_forms_app:delete_article' article.id %}">
                     <img src="{% static 'images/statusx_op.gif' %}" title="Delete"
                          alt="Delete article" />
                     </a>
                </td>

            </tr>
        {% endfor %}
        <a href="{% url 'my_forms_app:delete_all' %}" class="btn btn-default">
                     Delete_all_articles</a>
    </table>
{% else %}
    <p>The list of articles is empty.</p>
{% endif %}
{% endblock %}

my_forms_app/templates/app/list_authors.html
{% extends "base_template.html" %}
{% block title %}
    {{ title }}
{% endblock %}
{% block body_app %}
{% if author_list %}
    <ul class="list-group">
        {{ author_list.errors }}
        {% for author in author_list %}
            <li class="list-group-item">
                <span class="badge">

                    <a href="{% url 'my_forms_app:add_article' %}">
                        <span class="glyphicon glyphicon-plus"></span>
                   </a>

                </span>
                    {{ author.first_name }}
                    {{ author.last_name }}
                    {{ author.birth_date }}
            </li>
        {% endfor %}


    </ul>
        <a href="{% url 'my_forms_app:list_articles' %}" class="btn btn-default">
                     All_article</a>
{% else %}
    <p>The list of authors is empty.</p>
{% endif %}
{% endblock %}