app_adress_book/urls.py
from django.conf.urls import url
from . import views
__author__ = 'user'


urlpatterns = [
    url(r'^$', views.CountryView.as_view(), name='country'),
    url(r'^city/(?P<pk>[0-9]+)/$', views.CityView.as_view(), name='city'),
    url(r'^city/adress/(?P<pk>[0-9]+)/$', views.AdressView.as_view(),
        name='adress'),
    url(r'^(?P<pk>[0-9]+)/$', views.PersonView.as_view(),
        name='person'),
    url(r'^city/see_all/(?P<pk>[0-9]+)/$', views.PersonInCityView.as_view(),
        name='person_in_city'),
     url(r'^country/see_all/(?P<pk>[0-9]+)/$',
       views.PersonInCountryView.as_view(), name='person_in_country'),
]

my_calc/urls.py
from django.conf.urls import url
from my_calc.views import get_name

urlpatterns = [
    url(r'^$', get_name, name='name'),
    ]

test_proj/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^app_name/', include('app_name.urls', namespace="app_name")),
    url(r'app_author/', include('app_author.urls', namespace="app_author")),
    url(r'app_adress_book/country/', include('app_adress_book.urls',
                                     namespace="app_adress_book")),
    url(r'^test_form_app/', include('test_form_app.urls',
                                     namespace="test_form_app")),
    url(r'^test_model_form/', include('test_model_form.urls',
                                     namespace="test_model_form")),
    url(r'^my_forms_app/', include('my_forms_app.urls',
                                     namespace="my_forms_app")),
    url(r'^my_calc/', include('my_calc.urls',
                                     namespace="my_calc")),
]

app_adress_book/models.py
from django.db import models


# Create your models here.
class Country(models.Model):
    country_name = models.CharField(max_length=200)

    def __str__(self):
        return self.country_name


class City(models.Model):
    city_name = models.CharField(max_length=200)
    country = models.ForeignKey(Country)

    def __str__(self):
        return self.city_name


class Adress(models.Model):
    adress = models.CharField(max_length=200)
    city = models.ForeignKey(City)

    def __str__(self):
        return self.adress


class Person(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    date_birth = models.DateField()
    adress = models.ManyToManyField(Adress)

    def __str__(self):
        return "%s %s" % (self.first_name, self.last_name)

app_adress_book/views.py
from django.views import generic
from .models import Country, City, Adress, Person


# Create your views here.
class CountryView(generic.ListView):
    template_name = 'apps/country.html'
    context_object_name = 'country_list'
    model = Country

    def get_context_data(self, **kwargs):
        context = super(CountryView, self).get_context_data(**kwargs)
        context['title'] = "app_adress_book"
        return context


class CityView(generic.ListView):
    template_name = 'apps/city.html'
    context_object_name = 'city_list'

    def get_queryset(self):
        country_id = self.kwargs['pk']
        return City.objects.filter(country__id=country_id)

    def get_context_data(self, **kwargs):
        context = super(CityView, self).get_context_data(**kwargs)
        context['title'] = "app_adress_book"
        return context


class AdressView(generic.ListView):
    template_name = 'apps/adress.html'
    context_object_name = 'adress_list'
    model = Adress

    def get_queryset(self):
        city_id = self.kwargs['pk']
        return Adress.objects.filter(city__id=city_id)

    def get_context_data(self, **kwargs):
        context = super(AdressView, self).get_context_data(**kwargs)
        context['title'] = "app_adress_book"
        return context


class PersonView(generic.ListView):
    template_name = 'apps/person.html'
    context_object_name = 'person_list'
    model = Person

    def get_queryset(self):
        adress_id = self.kwargs['pk']
        return Person.objects.filter(adress__id=adress_id)

    def get_context_data(self, **kwargs):
        context = super(PersonView, self).get_context_data(**kwargs)
        context['title'] = "app_adress_book"
        return context


class PersonInCityView(generic.ListView):
    template_name = 'apps/all_person_city.html'
    context_object_name = 'person_list'
    model = Person

    def get_queryset(self):
        city_id = self.kwargs['pk']
        return Person.objects.filter(adress__city__id=city_id)

    def get_context_data(self, **kwargs):
        context = super(PersonInCityView, self).get_context_data(**kwargs)
        context['title'] = "app_adress_book"
        return context


class PersonInCountryView(generic.ListView):
    template_name = 'apps/all_person_country.html'
    context_object_name = 'person_list'
    model = Person

    def get_queryset(self):
        country_id = self.kwargs['pk']
        return Person.objects.filter(adress__city__country__id=country_id)

    def get_context_data(self, **kwargs):
        context = super(PersonInCountryView, self).get_context_data(**kwargs)
        context['title'] = "app_adress_book"
        return context

app_adress_book/templates/apps/adress.html
{% extends "base_template.html" %}
{% block title %}
    {{ title }}
{% endblock %}
{% block body_app %}
<script>
    document.getElementById("3").style = "color:green"
</script>
{% if adress_list %}
    <ul>
            {% for adress in adress_list %}
            <li>
                  <a href="{% url 'app_adress_book:person' adress.id %}">
                    {{ adress.adress }}
                  </a>
            </li>
         {% endfor %}
    </ul>
{% else %}
    <p>No apps are available.</p>
{% endif %}
{% endblock %}

app_adress_book/templates/apps/all_person_city.html
{% extends "base_template.html" %}
{% block title %}
   {{ title }}
{% endblock %}
{% block body_app %}
<script>
    document.getElementById("3").style = "color:green"
</script>
{% if person_list %}
    <ul>
            {% for person in person_list %}
            <li>
                {{ person.first_name }} {{ person.last_name }}
                {{ person.date_birth }}
            </li>
         {% endfor %}
    </ul>
{% else %}
    <p>No apps are available.</p>
{% endif %}
{% endblock %}

app_adress_book/templates/apps/all_person_country.html
{% extends "base_template.html" %}
{% block title %}
   {{ title }}
{% endblock %}
{% block body_app %}
<script>
    document.getElementById("3").style = "color:green"
</script>
{% if person_list %}
    <ul>
            {% for person in person_list %}
            <li>
                {{ person.first_name }} {{ person.last_name }}
                {{ person.date_birth }}
            </li>
         {% endfor %}
    </ul>
{% else %}
    <p>No apps are available.</p>
{% endif %}
{% endblock %}

app_adress_book/templates/apps/city.html
{% extends "base_template.html" %}
{% block title %}
   {{ title }}
{% endblock %}
{% block body_app %}
<script>
    document.getElementById("3").style = "color:green"
</script>
{% if city_list %}
    <ul>

            {% for city in city_list %}

           <li>
                  <a href="{% url 'app_adress_book:adress' city.id %}">
                    {{ city.city_name }}
                  </a>
               <a href="{% url 'app_adress_book:person_in_city' city.id %}">
               See all people</a>
            </li>
         {% endfor %}
    </ul>
{% else %}
    <p>No apps are available.</p>
{% endif %}
{% endblock %}

app_adress_book/templates/apps/country.html
{% extends "base_template.html" %}
{% block title %}
   {{ title }}
{% endblock %}
{% block body_app %}
<script>
    document.getElementById("3").style = "color:green"
</script>
{% if country_list %}
    <ul>
        {% for country in country_list %}
            <li>
                  <a href="{% url 'app_adress_book:city' country.id %}">
                    {{ country.country_name }}
                  </a>
                <a href="{% url 'app_adress_book:person_in_country' country.id%}">
                    See all people
                  </a>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No apps are available.</p>
{% endif %}
{% endblock %}

app_adress_book/templates/apps/person.html
{% extends "base_template.html" %}
{% block title %}
   {{ title }}
{% endblock %}
{% block body_app %}
<script>
    document.getElementById("3").style = "color:green"
</script>
{% if person_list %}
    <ul>
            {% for person in person_list %}
            <li>
                {{ person.first_name }} {{ person.last_name }}
                {{ person.date_birth }}
            </li>
         {% endfor %}
    </ul>
{% else %}
    <p>No apps are available.</p>
{% endif %}
{% endblock %}